Made the new checks-parameter available in the github action.

diff --git a/v1/action.yml b/v1/action.yml
--- a/v1/action.yml
+++ b/v1/action.yml
@@ -10,8 +10,12 @@ inputs:
     required: true
   minimum-grade:
     description: 'The minimum grade that will make the scan pass'
-    required: true
-    default: 'D'
+    required: false
+    default: 'F'
+  checks:
+    description: 'A comma-separated list of the specific checks to run'
+    required: false
+    default: ''
 
 runs:
   using: "composite"
@@ -26,6 +30,7 @@ runs:
           -D "$headers_file" \
           --data-urlencode "url=${{ inputs.target-url }}" \
           --data-urlencode "minimum_grade=${{ inputs.minimum-grade }}" \
+          --data-urlencode "checks=${{ inputs.checks }}" \
           https://ephort.dk/scanner/api/v1/scan
         )
 
@@ -36,18 +41,27 @@ runs:
         # Extract the status code from the headers
         status_code=$(echo "$headers" | awk -v RS='\r?\n' '/^HTTP/{print $2}')
 
-        grade=$(echo $response | jq -r '.grade')
+        if [ -z "${{ inputs.checks }}" ]
+        then
+          grade=$(echo $response | jq -r '.grade')
+        else
+          grade=""
+        fi
+
         message=$(echo $response | jq -r '.message')
 
         if [ "$status_code" == "200" ]; then
-          echo "Security Scan complete and grade met expectations."
+          echo "Security Scan complete and met expectations."
         elif [ "$status_code" == "400" ] && [ "$message" == "Invalid URL" ]; then
           echo "Invalid URL provided. Please check the URL and try again."
           exit 1
         elif [ "$status_code" == "400" ] && [ "$message" == "Invalid minimum grade" ]; then
           echo "Invalid minimum grade. Please check the minimum_grade parameter and try again."
           exit 1
-        else
+        elif [ -z "${{ inputs.checks }}" ]
           echo "Security Scan failed as it did not meet grade expectations. The actual grade was $grade."
+          exit 1
+        else
+          echo "Security Scan failed as one or more of the checks failed."
           exit 1
         fi
